### ISSUE TITLE
Morgan and York

### ISSUE THREAD

**Issue by vielmetti** [mwotton/aa-coworking#5]
Packard Road between Jorn and Coler. Several long tables (n=8) in the front, and more in the back. No power outlets in the front but there is one in the back, bring a power strip. 

Full deli, coffee bar. They sell wine and beer but you can't open a bottle on site. Espresso, $2.25.

Not "downtown", so it might need another section in the list.

**Comment by mwotton** [comment]
sounds good! you know the area better than me, just choose a name & PR me.

**Comment by vielmetti** [comment]
PR is in!
